version: "3.7"

services:
  mysql:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - authdb:/var/lib/mysql
  app:
    image: node:16    
    build: .
    command: sh -c "npm install && npm start"
    depends_on: 
      - mysql
    working_dir: /usr/src/app
    volumes:
      - ./:/app
    env_file: ./.env
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_DOCKER_PORT=$MYSQLDB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes:
  authdb: